# -*- coding: utf-8 -*-
"""Materi-9-Decision-Tree-Syafrudin Fahrul Anas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1okDiAUJ1rvoMuFGdtbqoatKbXCohkKMs
"""

from sklearn import tree

# Database Gerbang Logika AND
# X = Data, y = Target

x = [[0 , 0, 0],
[0 , 5, 0],
[0 , 0, 5],
[0 , 5, 5],
[5 , 5, 0],
[5 , 0, 5],
[5 , 5, 5],
[10, 5, 5],
[5 , 10, 5],
[10, 10, 10]]

y = [0,0,0,5,5,5,10,10,5,0]

# Training and clasify

clf = tree.DecisionTreeClassifier()
clf = clf.fit(x,y)

# Prediction
print("Logika AND Metode Decision Tree")
print("Logika = Prediksi")
print("10 10 5 =",clf.predict([[10,10,5]]))
print("5 10 2 =",clf.predict([[5,10,2]]))
print("2 0 10 =",clf.predict([[2,0,10]]))
print("5 0 2 =",clf.predict([[5,0,2]]))
print("0 0 2 =",clf.predict([[0,0,2]]))
print("2 10 2 =",clf.predict([[2,10,2]]))
print("1 12 5 =",clf.predict([[1,12,5]]))
print("2 2 6 =",clf.predict([[2,2,6]]))
print("10 5 7 =",clf.predict([[10,5,7]]))

from google.colab import drive
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt

# Mount Google Drive
drive.mount('/content/drive')

#path ke file di google drive
FileDB = '/content/drive/My Drive/modul9/Cosinus.txt' # Sesuaikan path file
Database = pd.read_csv(FileDB, sep=",", header=0)

#Lihat Data
print("--------------------")
print(Database)

# x data, y data
x = Database[["Feature"]]# Replace with your actual column names
y = Database.Target

reg = DecisionTreeRegressor(random_state=1)
reg = reg.fit(x,y)

# Display predicted data
xx = np.arange(1, 21, 1)
n = len(xx)
print("xx(i) Decission Tree")
for i in range(n):
  y_dct = reg.predict([[xx[i]]])
  print('{:.2f}'.format(xx[i]),y_dct)

# plot the predicted data
y_dct2 = reg.predict(x)
plt.figure()
plt.plot(x, y_dct2, color='red')
plt.scatter(x, y, color='blue')
plt.title('Prediksi Data Decision Tree Cosinus')
plt.xlabel('x')
plt.ylabel('y')
plt.legend(['Decision Tree', 'data'], loc=2)
plt.show()